### ISSUE TITLE
load model failed

### ISSUE THREAD

**Issue by 18140663659** [Beomi/InfiniTransformer#9]
I downloaded the gemma model and got an error when loading it locally.

code:
pretrained_model = GemmaForCausalLM.from_pretrained("./model")

error:
Traceback (most recent call last):
  File "test_basic.py", line 36, in <module>
    pretrained_model = GemmaForCausalLM.from_pretrained("./model")
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/modeling_utils.py", line 3550, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/models/gemma/modeling_gemma.py", line 1368, in __init__
    self.model = GemmaModel(config)
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/models/gemma/modeling_gemma.py", line 1119, in __init__
    [
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/models/gemma/modeling_gemma.py", line 1120, in <listcomp>
    GemmaDecoderLayer(config, layer_idx)
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/models/gemma/modeling_gemma.py", line 877, in __init__
    self.self_attn = GEMMA_ATTENTION_CLASSES[config._attn_implementation](
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/models/gemma/modeling_gemma.py", line 709, in __init__
    self.segment_size = config.segment_size
  File "/root/data/vjuicefs_translation_002/11120000/InfiniTransformer/src/transformers/src/transformers/configuration_utils.py", line 263, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'GemmaConfig' object has no attribute 'segment_size'

**Comment by Beomi** [comment]
It seems like you are using outdated code.
could you retry with git pull this repository and try again? (you need to run test_train.small.gemma.py file)

**Comment by 18140663659** [comment]
I use the new version of the code and modify the gamma configuration file. The current results of running test_basic.py are as follows：

class GemmaConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`GemmaModel`]. It is used to instantiate an Gemma
    model according to the specified arguments, defining the model architecture. Instantiating a configuration with the
    defaults will yield a similar configuration to that of the Gemma-7B.

    e.g. [google/gemma-7b](https://huggingface.co/google/gemma-7b)

    Configuration objects inherit from [`PretrainedConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.


    Args:
        vocab_size (`int`, *optional*, defaults to 256000):
            Vocabulary size of the Gemma model. Defines the number of different tokens that can be represented by the
            `inputs_ids` passed when calling [`GemmaModel`]
        hidden_size (`int`, *optional*, defaults to 3072):
            Dimension of the hidden representations.
        intermediate_size (`int`, *optional*, defaults to 24576):
            Dimension of the MLP representations.
        num_hidden_layers (`int`, *optional*, defaults to 28):
            Number of hidden layers in the Transformer decoder.
        num_attention_heads (`int`, *optional*, defaults to 16):
            Number of attention heads for each attention layer in the Transformer decoder.
        num_key_value_heads (`int`, *optional*, defaults to 16):
            This is the number of key_value heads that should be used to implement Grouped Query Attention. If
            `num_key_value_heads=num_attention_heads`, the model will use Multi Head Attention (MHA), if
            `num_key_value_heads=1 the model will use Multi Query Attention (MQA) otherwise GQA is used. When
            converting a multi-head checkpoint to a GQA checkpoint, each group key and value head should be constructed
            by meanpooling all the original heads within that group. For more details checkout [this
            paper](https://arxiv.org/pdf/2305.13245.pdf). If it is not specified, will default to
            `num_attention_heads`.
        head_dim (`int`, *optional*, defaults to 256):
            The attention head dimension.
        hidden_act (`str` or `function`, *optional*, defaults to `"gelu_pytorch_tanh"`):
            The legacy activation function. It is overwritten by the `hidden_activation`.
        hidden_activation (`str` or `function`, *optional*):
            The non-linear activation function (function or string) in the decoder. Will default to `"gelu_pytorch_tanh"`
            if not specified. `"gelu_pytorch_tanh"` uses an approximation of the `"gelu"` activation function.
        max_position_embeddings (`int`, *optional*, defaults to 8192):
            The maximum sequence length that this model might ever be used with.
        initializer_range (`float`, *optional*, defaults to 0.02):
            The standard deviation of the truncated_normal_initializer for initializing all weight matrices.
        rms_norm_eps (`float`, *optional*, defaults to 1e-06):
            The epsilon used by the rms normalization layers.
        use_cache (`bool`, *optional*, defaults to `True`):
            Whether or not the model should return the last key/values attentions (not used by all models). Only
            relevant if `config.is_decoder=True`.
        pad_token_id (`int`, *optional*, defaults to 0):
            Padding token id.
        eos_token_id (`int`, *optional*, defaults to 1):
            End of stream token id.
        bos_token_id (`int`, *optional*, defaults to 2):
            Beginning of stream token id.
        tie_word_embeddings (`bool`, *optional*, defaults to `True`):
            Whether to tie weight embeddings
        rope_theta (`float`, *optional*, defaults to 10000.0):
            The base period of the RoPE embeddings.
        attention_bias (`bool`, defaults to `False`, *optional*, defaults to `False`):
            Whether to use a bias in the query, key, value and output projection layers during self-attention.
        attention_dropout (`float`, *optional*, defaults to 0.0):
            The dropout ratio for the attention probabilities.

    ```python
    >>> from transformers import GemmaModel, GemmaConfig

    >>> # Initializing a Gemma gemma-7b style configuration
    >>> configuration = GemmaConfig()

    >>> # Initializing a model from the gemma-7b style configuration
    >>> model = GemmaModel(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "gemma"
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        vocab_size=256000,
        hidden_size=3072,
        intermediate_size=24576,
        num_hidden_layers=28,
        num_attention_heads=16,
        num_key_value_heads=16,
        head_dim=256,
        hidden_act="gelu_pytorch_tanh",
        hidden_activation=None,
        max_position_embeddings=8192,
        initializer_range=0.02,
        rms_norm_eps=1e-6,
        use_cache=True,
        pad_token_id=0,
        eos_token_id=1,
        bos_token_id=2,
        tie_word_embeddings=True,
        rope_theta=10000.0,
        attention_bias=False,
        attention_dropout=0.0,
        memory_size=2048,
        segment_size=16,
        **kwargs,
    ):
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.head_dim = head_dim
        self.num_key_value_heads = num_key_value_heads
        self.hidden_act = hidden_act
        self.hidden_activation = hidden_activation
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        
       # add 
        self.memory_size = memory_size
        self.segment_size = segment_size   

        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )

result:

Short Text Loss
tensor(4.1080, device='cuda:0', grad_fn=<NllLossBackward0>)
Long Text Loss
tensor(8.9868, device='cuda:0', grad_fn=<NllLossBackward0>)
backprop done
generated_sequence: <bos>This work introduces an efficient method to scale Transformer-based language representation learning for sequenceệ C++Parial
Generated:
<bos>This work introduces an efficient method to scale Transformer-based language models while maintaining their capabilities beyond its use-case-independent evaluation of neural representations and demonstrates that the ability to model capacity for model for improving the language model

**Comment by Beomi** [comment]
it seems working then ;)

**Comment by 18140663659** [comment]
train result as follow, it is right?

{'train_runtime': 473.0422, 'train_samples_per_second': 81.557, 'train_steps_per_second': 2.549, 'train_loss': 3.0520837755740975, 'epoch': 1.0}                          
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1206/1206 [07:13<00:00,  2.78it/s]
wandb: 
wandb: Run history:
wandb:         train/epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:   train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:     train/grad_norm ▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: train/learning_rate ████▇▇▇▇▇▆▆▆▆▆▆▅▅▅▅▅▅▄▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▁▁▁
wandb:          train/loss ▂█▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:               total_flos 2.936106269540352e+16
wandb:              train/epoch 1.0
wandb:        train/global_step 1206
wandb:          train/grad_norm 4.71875
wandb:      train/learning_rate 0.0
wandb:               train/loss 2.5089
wandb:               train_loss 3.05208
wandb:            train_runtime 473.0422
wandb: train_samples_per_second 81.557
wandb:   train_steps_per_second 2.549
